/*
 * DO NOT EDIT THIS FILE, it is auto-generated. It will be updated automatically.
 * All changes done to this file will be lost upon re-running the 'silence createapi' command.
 * If you want to create new API methods, define them in a new file.
 *
 * Silence is built and maintained by the DEAL research group at the University of Seville.
 * You can find us at https://deal.us.es
 */

"use strict";

import { BASE_URL, requestOptions } from './common.js';

const usuariosAPI_auto = {

    /**
    * Gets all usuarios
    */
    getAll: async function() {
        let response = await axios.get(`${BASE_URL}/usuarios`,requestOptions);
        return response.data;
    },

    /**
    * Gets an entry from 'usuarios' by its primary key
    */
    getById: async function(email) {
        let response = await axios.get(`${BASE_URL}/usuarios/${email}`,requestOptions);
        return response.data[0];
    },

    /**
    * Creates a new entry in 'usuarios'
    */
    create: async function(formData, ) {
        let response = await axios.post(`${BASE_URL}/usuarios`,formData, requestOptions);
        return response.data;
    },

    /**
    * Updates an existing entry in 'usuarios' by its primary key
    */
    update: async function(formData, email) {
        let response = await axios.put(`${BASE_URL}/usuarios/${email}`,formData, requestOptions);
        return response.data;
    },

    /**
    * Deletes an existing entry in 'usuarios' by its primary key
    */
    delete: async function(email) {
        let response = await axios.delete(`${BASE_URL}/usuarios/${email}`,requestOptions);
        return response.data;
    },
};

export {usuariosAPI_auto};